### ISSUE TITLE
About Api

### ISSUE THREAD

**Issue by serkandyck** [tangqi92/BuildingBlocks#2]
Hello this project using api and get data title image and date link and building block listing but clicking block opening webviev right ?

**Comment by tangqi92** [comment]
Yes, i know, use webview is kind of lazy way.

**Comment by serkandyck** [comment]
i have little api but no open webview link endpoint

**Comment by troyliu0105** [comment]
I wanna try another way to load content... parse a html then show it in a View or directly show "body" element in JSON with CSS. @asdstyle33 ...... == maybe paring a html file is better...

**Comment by tangqi92** [comment]
@troyliu0105 Do you know how to get specific content through the API? You can get it from: https://github.com/izzyleung/ZhihuDailyPurify/wiki/%E7%9F%A5%E4%B9%8E%E6%97%A5%E6%8A%A5-API-%E5%88%86%E6%9E%90 and E.g: http://news-at.zhihu.com/api/4/news/3892357

**Comment by troyliu0105** [comment]
ye.. i have read this wiki.... i tried to do that several hour ago.. but it's a little hard for me to save the all the fields of object to database. So I just use Serialization to save the whole List. 

and later missions
1. try to use start-image;
2. abandon WebViewActivity, normal View(TextView, ImageView...) instead.
3. Push notification...

**Comment by tangqi92** [comment]
@troyliu0105 Nice! I'm looking forward to your follow-up.
