### ISSUE TITLE
AboutActivity crush issue

### ISSUE THREAD

**Issue by KaiWangCanada** [tangqi92/BuildingBlocks#3]
in about activity, scroll up till the green android avatar bar is completely hidden, then scroll down. it will crush. the device is galax nexus. also thank you for the toy ^^

**Comment by tangqi92** [comment]
@KaiWangCanada Bug has been fixed, releases and code has been sync. Finally, thank you for your support :D

**Comment by KaiWangCanada** [comment]
Thank you for the contribution :D It's a great work! Btw, I saw it from 开发者头条

奈业 iPhone 魉
